baseURL = "https://improve1024.github.io/blog/" 
googleAnalytics = "" # UA-XXXXXXXX-X/G-XXXXXXXXXX
defaultContentLanguage = "zh-hans"
theme = "maupassant" 
title = "不能止步" 

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140

# disqusShortname = "yourdiscussshortname" ## 是否开启disqus评论，不要和utteranc同时开启

[author]
name = "Jimmy Liu"

[params]
author = "Jimmy Liu" 
busuanzi = true #启用不算子网页统计
# description = "专注于IT互联网，包括但不限于Go语言(golang)、Java、Android、Python、项目管理、抖音分析、软件架构等" 
googleAd = "" #ca-pub-xxxxxxxxxxxxxx
keywords = "java, python, kotlin, golang, go语言, docker, k8s, kubernates, 软件架构, 微服务, 云原生" 
localSearch = true # 启用本地搜索
subtitle = "专注于分布式服务、云原生设计" 

# 这里我存放在了主题的static文件夹里，根目录的似乎也可以
customCSS = ['douban.css', 'other.css']
# if ['custom.css'], load '/static/css/custom.css' file
customJS = ['douban.js']
# if ['custom.js'], load '/static/js/custom.js' file

# 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
toc = true # 是否开启目录

## 友情链接，可以多个

[[params.links]]
name = "不能止步"
title = "不能止步"
url = "https://blog.csdn.net/l460133921/"

## 侧边栏广告位
[[params.ads]]
img = "https://img.alicdn.com/imgextra/i3/O1CN01olndvC20XTHIIKZkq_!!6000000006859-0-tps-3840-720.jpg"
title = "云服务器省钱攻略"
url = "https://www.aliyun.com/minisite/goods?userCode=gg98qkpg"
[[params.ads]]
img = "https://img.alicdn.com/imgextra/i3/O1CN01olndvC20XTHIIKZkq_!!6000000006859-0-tps-3840-720.jpg"
title = "助力产业智慧升级，云服务器首年88元起，更有千元代金券礼包免费领！"
url = "https://cloud.tencent.com/act/cps/redirect?redirect=1048&cps_key=14ff722692ac784fa8c3301c8c28d924&from=console"
[[params.ads]]
img = "https://img.alicdn.com/tfs/TB1hblJl7Y2gK0jSZFgXXc5OFXa-750-400.jpg"
title = "【渠道专享低折扣】11月特惠 限时2折"
url = "https://www.aliyun.com/acts/limit-buy?userCode=jdg9oj97"

## 配置 utteranc评论,教程参考 https://utteranc.es/
[params.utteranc]
enable = true 
issueTerm = "pathname" 
repo = "improve1024/blog" ##换成自己得
theme = "github-light" 
## 配置 waline 评论系统,教程参考 https://waline.js.org/
[params.waline]
enable = false 
placeholder = "说点什么吧..." 
serverURL = "Your waline serverURL" #换成你的serverURL
## 开启版权声明，协议名字和链接都可以换
[params.cc]
enable = false
link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"
name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"

## 配置代码高亮
[markup]
[markup.highlight]
lineNos = true
style = "github"

## 配置网站菜单

[menu]

# [[menu.main]]
# identifier = "tools"
# name = "工具"
# url = "/tools/"
# weight = 2

[[menu.main]]
identifier = "archives"
name = "归档"
url = "/archives/"
weight = 3

# [[menu.main]]
# identifier = "about"
# name = "关于"
# url = "/about/"
# weight = 4
